--CREATE TABLES FOOD ORDER

CREATE TABLE UserPrivileges
(
	ID INT IDENTITY PRIMARY KEY,
	Privilege VARCHAR(20) UNIQUE NOT NULL
)
GO

CREATE TABLE City
(
	ID INT IDENTITY PRIMARY KEY,
	Name VARCHAR(25) NOT NULL
)
GO
CREATE TABLE District
(
	ID INT IDENTITY PRIMARY KEY,
	CityID INT FOREIGN KEY REFERENCES City(ID) ON DELETE CASCADE NOT NULL,
	Name VARCHAR(25) NOT NULL
)
GO
CREATE TABLE Users
(
	ID INT IDENTITY PRIMARY KEY,
	UserName VARCHAR(100) NOT NULL UNIQUE,
	UserPassword VARCHAR(18) NOT NULL,
	UserCity INT FOREIGN KEY REFERENCES City(ID) NOT NULL,
	UserDistrict INT FOREIGN KEY REFERENCES District(ID) NOT NULL,
	UserEmail VARCHAR(100) NOT NULL,
	UserPhone VARCHAR(30) NOT NULL,
	PrivilegeID INT FOREIGN KEY REFERENCES UserPrivileges(ID) ON DELETE CASCADE NOT NULL ,
	TrueAdmin BIT DEFAULT 0 NULL
)
GO

CREATE TABLE Companies
(
	ID INT IDENTITY PRIMARY KEY,
	UserID INT FOREIGN KEY REFERENCES Users(ID) ON DELETE CASCADE NOT NULL,
	CompanyName VARCHAR(50) UNIQUE NOT NULL,
	CompanyEmail VARCHAR(50) NOT NULL,
	CompanyPhone VARCHAR(20) NOT NULL,
	CompanyDistrict INT FOREIGN KEY REFERENCES District(ID) ON DELETE CASCADE NOT NULL,
	CompanyWorkHoursStart INT NOT NULL,
	CompanyWorkHoursEnd INT NOT NULL,
	CompanyServiceTime INT NOT NULL,
	CompanyMinimumPrice INT NOT NULL,
	CompanyPoint FLOAT DEFAULT 0,
	CompanyReviewCount INT DEFAULT 0
)
GO
CREATE TABLE CompanyFoods
(
	ID INT IDENTITY PRIMARY KEY,
	FoodName VARCHAR(30) NOT NULL,
	FoodPrice INT NOT NULL,
	FoodType VARCHAR(30) NULL,
	CompanyID INT FOREIGN KEY REFERENCES Companies(ID) ON DELETE CASCADE NOT NULL
)
GO

CREATE TABLE FoodCategories
(
	ID INT IDENTITY PRIMARY KEY,
	Name VARCHAR(20) UNIQUE
)
GO